/// This file is auto-generated by Obfuz. Do not modify it.
///
/// Version: 0
/// SecretKey: Obfuz
/// OpCodeCount: 256

namespace Obfuz.EncryptionVM
{
    public class GeneratedEncryptionVirtualMachine : Obfuz.EncryptorBase
    {
        private const int kOpCodeBits = 8;
        private const int kOpCodeCount = 256;
        private const int kOpCodeMask = 255;
        private readonly int[] _secretKey;
        public GeneratedEncryptionVirtualMachine(byte[] secretKey)
        {
            this._secretKey = ConvertToIntKey(secretKey);
        }
        public override int OpCodeCount => kOpCodeCount;
        public override int Encrypt(int value, int opts, int salt)
        {
            return value;
        }
        public override int Decrypt(int value, int opts, int salt)
        {
            return value;
        }
    }
}