#if USE_ILRUNTIME
using UnityEditor;
using UnityEngine;
using System;
using System.Collections.Generic;
using System.IO;
using ILRuntime.Runtime.CLRBinding;
using ILRuntime.Runtime.Enviorment;
using ILRAppDomain = ILRuntime.Runtime.Enviorment.AppDomain;
using System.Reflection;

[Obfuscation(Exclude = true)]
public class ILRuntimeCLRBinding
{
	[MenuItem("ILRuntime/生成跨域继承适配器")]
	public static void GenerateCrossbindAdapter()
	{
		// 由于跨域继承特殊性太多，自动生成无法实现完全无副作用生成，所以这里提供的代码自动生成主要是给大家生成个初始模版，简化大家的工作
		// 大多数情况直接使用自动生成的模版即可，如果遇到问题可以手动去修改生成后的文件，因此这里需要大家自行处理是否覆盖的问题
		List<Type> classType = new List<Type>();
		ILRLaunch.collectCrossInheritClass(classType);
		foreach(var item in classType)
		{
			generateAdapter(item);
		}
		AssetDatabase.Refresh();
	}
	[MenuItem("ILRuntime/通过自动分析热更DLL生成CLR绑定")]
	public static void GenerateCLRBindingByAnalysis()
	{
		// 用新的分析热更dll调用引用来生成绑定代码
		Debug.Log("如果自动分析有报错,先尝试重新编译热更工程后再分析,如果生成完毕后SQLite有报错,则可能是命名空间引起的,将其中的错误相关代码还原即可");
		ILRAppDomain domain = new ILRAppDomain();
		string dllPath = FrameDefine.P_STREAMING_ASSETS_PATH + FrameDefine.ILR_FILE_NAME;
		using (FileStream fs = new FileStream(dllPath, FileMode.Open, FileAccess.Read))
		{
			domain.LoadAssembly(fs);
			//这里需要注册所有热更DLL中用到的跨域继承Adapter，否则无法正确抓取引用
			ILRLaunch.registeCrossAdaptor(domain);
			BindingCodeGenerator.GenerateBindingCode(domain, FrameDefine.P_SCRIPT_GAME_PATH + "ILRuntime/GeneratedCLRBinding");
		}
		AssetDatabase.Refresh();
	}
	//------------------------------------------------------------------------------------------------------------
	protected static void generateAdapter(Type type, string nameSpace = "HotFix")
	{
		string prePath = FrameDefine.P_SCRIPT_GAME_PATH + "ILRuntime/GeneratedCrossBinding/";
		string fullFileName = prePath + type.Name + "Adapter.cs";
		FileUtility.createDir(prePath);
		using (StreamWriter sw = new StreamWriter(fullFileName))
		{
			sw.WriteLine(CrossBindingCodeGenerator.GenerateCrossBindingAdapterCode(type, nameSpace));
		}
		// 生成热更工程中对应的派生类,用于重写所有的虚函数,只是因为ILR本身的原因需要对虚函数进行重写
		ClassTypeGenerator generator = new ClassTypeGenerator();
		generator.generateILRClass(type, FrameDefine.F_HOT_FIX_PATH + "Game/ILRInherit_AutoGenerated/");
	}
}
#endif