using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Compilation;
using UnityEditor.PackageManager;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEditorInternal;
#if USE_HYBRID_CLR
using HybridCLR.Editor.Settings;
#endif
#if USE_OBFUZ
using Obfuz.Settings;
#endif
using static EditorDefine;
using static EditorFileUtility;
using static FileUtility;
using static StringUtility;
using static FrameBaseDefine;
using static FrameDefine;
using static FrameMacro;

// 挂接GameEntry的结果
public enum ATTACK_GAME_ENTRY_RESULT : byte
{
    SUCCESS,                    // 挂接成功
    MISSING_START_SCENE,        // 缺少启动场景
    MISSION_GAME_ENTRY_TYPE,    // 缺少GameEntry类型
    MissingGameEntryNode,       // 缺少GameEntry节点
    Cancelled,                  // 用户取消保存场景
}

public enum HYBRIDCLR_OBFUZ_STATE : byte
{
    NONE,                   // 无初始化状态
    INSTALL_HYBRIDCLR,      // 正在安装HybridCLR
    INSTALL_OBFUZ,          // 正在安装Obfuz
    ADD_DEFINE,             // 正在添加宏
    INIT_SETTING,           // 正在写插件设置
}

public class MenuInit
{
    private const string MENU_NAME = MENU_ROOT_NAME + "初始化/";														// 初始化菜单根路径
    private const string PACKAGE_NAME = "com.zhourui.myframework";														// 包名
    private const string PROJECT_TEMPLATE_PATH = "Packages/" + PACKAGE_NAME + "/ProjectTemplate~/";						// 包内项目模板目录
    private const string GAME_ENTRY_NODE_NAME = "GameEntry";															// 启动节点名称
    private const string GAME_ENTRY_TYPE_NAME = "GameEntry";															// 启动脚本类型名,如果有命名空间需要改成完整名
    private const string SESSION_PENDING_ATTACH_GAMEENTRY = "MyFramework.PendingAttachGameEntry";						// 等待挂接GameEntry的Session标记
    private const string SESSION_PENDING_PACKAGE_PATH = "MyFramework.PendingAttachGameEntry.PackagePath";				// 请求挂接时的包真实路径
    private const string SESSION_HYBRIDCLR_OBFUZ_STATE = "MyFramework.HybridCLRObfuz.State";							// HybridCLR和Obfuz初始化状态
    private const string HYBRIDCLR_PACKAGE_ID = "com.code-philosophy.hybridclr";										// HybridCLR包名
    private const string OBFUZ_PACKAGE_ID = "com.code-philosophy.obfuz";												// Obfuz包名
    private const string HYBRIDCLR_PACKAGE_URL = "https://gitee.com/focus-creative-games/hybridclr_unity.git";			// HybridCLR安装地址
    private const string OBFUZ_PACKAGE_URL = "https://gitee.com/focus-creative-games/obfuz.git";						// Obfuz安装地址
    private const string OBFUZ_OUTPUT_PATH = "Assets/Scripts/AutoGenerated/Obfuz/GeneratedEncryptionVirtualMachine.cs";	// Obfuz生成文件路径
    private const string HYBRIDCLR_AOT_OUTPUT_PATH = "Scripts/AutoGenerated/HybridCLRGenerate/AOTGenericReferences.cs"; // HybridCLR AOT引用生成文件路径
    private static UnityEditor.PackageManager.Requests.AddRequest mPackageAddRequest;									// 当前Package安装请求
    [MenuItem(MENU_NAME + "初始化框架", false, 0)]
    public static void initFramework()
    {
        doInit(false);
    }
    [MenuItem(MENU_NAME + "初始化框架+HybridCLR+Obfuz", false, 0)]
    public static void initFrameworkHybridCLRObfuz()
    {
        doInit(true);
    }
    //---------------------------------------------------------------------------------------------------------------------------
    // Unity重新编译并DomainReload以后,继续执行初始化中断的挂接流程
    [InitializeOnLoadMethod]
    private static void initOnLoad()
    {
        EditorApplication.delayCall += continueAttachGameEntryIfNeed;
        EditorApplication.delayCall += continueHybridCLRObfuzIfNeed;
    }
    // 初始化框架
    protected static void doInit(bool withHybridCLRObfuz)
    {
        fixActiveInputHandling();
        if (!copyProjectTemplateFiles(out bool needCompile))
        {
            clearPendingAttachGameEntry();
            return;
        }

        FrameEditorSettings.save();
        MenuSetting.createRuntimeSettinsFile();

        if (withHybridCLRObfuz)
        {
            requestInitHybridCLRObfuz();
        }

        AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);

        if (needCompile)
        {
            requestAttachGameEntryAfterCompile();
            Debug.Log("MyFramework模板脚本已复制,等待Unity编译完成后自动挂接GameEntry");
            return;
        }

        ATTACK_GAME_ENTRY_RESULT attachResult = attachGameEntryToStartScene(true);
        if (attachResult == ATTACK_GAME_ENTRY_RESULT.SUCCESS)
        {
            clearPendingAttachGameEntry();
            addStartSceneToBuildSettings();
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("MyFramework初始化完成");
            return;
        }

        if (attachResult == ATTACK_GAME_ENTRY_RESULT.MISSION_GAME_ENTRY_TYPE)
        {
            requestAttachGameEntryAfterCompile();
            Debug.Log("未找到GameEntry类型,等待Unity重新编译后自动挂接GameEntry");
            return;
        }

        clearPendingAttachGameEntry();
        Debug.LogError("MyFramework初始化失败,请检查模板文件是否完整");
    }
    // 修正Unity输入系统设置。
    // 框架和模板场景默认使用UnityEngine.Input和StandaloneInputModule,所以需要允许旧输入系统。
    protected static void fixActiveInputHandling()
    {
        System.Reflection.PropertyInfo property = typeof(PlayerSettings).GetProperty(
            "activeInputHandling",
            System.Reflection.BindingFlags.Static |
            System.Reflection.BindingFlags.Public |
            System.Reflection.BindingFlags.NonPublic
        );

        if (property == null)
        {
            Debug.LogWarning("当前Unity版本未找到PlayerSettings.activeInputHandling,请手动设置 Project Settings/Player/Active Input Handling 为 Both");
            return;
        }

        object currentValue = property.GetValue(null);
        if (currentValue != null && currentValue.ToString() == "Both")
        {
            return;
        }
        object bothValue;
        try
        {
            bothValue = Enum.Parse(property.PropertyType, "Both");
        }
        catch
        {
            Debug.LogWarning("当前Unity版本未找到Active Input Handling的Both选项,请手动设置 Project Settings/Player/Active Input Handling 为 Both");
            return;
        }

        property.SetValue(null, bothValue);
        Debug.Log("已将Active Input Handling设置为Both,以兼容MyFramework的旧输入接口和StandaloneInputModule");
    }
    // 拷贝ProjectTemplate~中的所有文件到工程根目录,保持原有相对路径
    protected static bool copyProjectTemplateFiles(out bool needCompile)
    {
        needCompile = false;
        string projectRootPath = getProjectRootPath();
        string templateFullPath = projectRootPath + PROJECT_TEMPLATE_PATH;
        if (!Directory.Exists(templateFullPath))
        {
            Debug.LogError("未找到项目模板目录: " + PROJECT_TEMPLATE_PATH);
            return false;
        }

        foreach (string sourceFullPathOrigin in findFilesNonAlloc(templateFullPath))
        {
            string sourceFullPath = sourceFullPathOrigin.Replace("\\", "/");
            string relativePath = sourceFullPath[templateFullPath.Length..];
            string targetFullPath = (projectRootPath + relativePath).Replace("\\", "/");
            if (File.Exists(targetFullPath))
            {
                Debug.Log("模板文件已存在,跳过: " + relativePath.Replace("\\", "/"));
                continue;
            }

            copyFile(sourceFullPath, targetFullPath);

            if (isScriptCompileFile(targetFullPath))
            {
                needCompile = true;
            }
        }
        return true;
    }
    // 请求编译完成后挂接GameEntry
    protected static void requestAttachGameEntryAfterCompile()
    {
        SessionState.SetBool(SESSION_PENDING_ATTACH_GAMEENTRY, true);
        SessionState.SetString(SESSION_PENDING_PACKAGE_PATH, getCurrentPackagePath());
        AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);
        CompilationPipeline.RequestScriptCompilation();
    }
    // 清理等待挂接GameEntry的Session标记
    protected static void clearPendingAttachGameEntry()
    {
        SessionState.SetBool(SESSION_PENDING_ATTACH_GAMEENTRY, false);
        SessionState.SetString(SESSION_PENDING_PACKAGE_PATH, string.Empty);
    }
    // 编译完成后继续挂接GameEntry
    protected static void continueAttachGameEntryIfNeed()
    {
        if (!SessionState.GetBool(SESSION_PENDING_ATTACH_GAMEENTRY, false))
        {
            return;
        }
        if (EditorApplication.isCompiling || EditorApplication.isUpdating)
        {
            EditorApplication.delayCall += continueAttachGameEntryIfNeed;
            return;
        }
        string pendingPackagePath = SessionState.GetString(SESSION_PENDING_PACKAGE_PATH, string.Empty);
        if (pendingPackagePath.isEmpty())
        {
            clearPendingAttachGameEntry();
            Debug.Log("检测到旧版本MyFramework残留挂接标记,已自动清理");
            return;
        }
        if (pendingPackagePath != getCurrentPackagePath())
        {
            clearPendingAttachGameEntry();
            Debug.Log("检测到MyFramework旧包残留挂接标记,已自动清理");
            return;
        }
        if (!hasStartScene())
        {
            clearPendingAttachGameEntry();
            Debug.Log("检测到残留的MyFramework初始化挂接标记,但启动场景不存在,已自动清理");
            return;
        }

        ATTACK_GAME_ENTRY_RESULT attachResult = attachGameEntryToStartScene(false);
        if (attachResult == ATTACK_GAME_ENTRY_RESULT.SUCCESS)
        {
            clearPendingAttachGameEntry();
            addStartSceneToBuildSettings();
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("MyFramework初始化完成,已自动挂接GameEntry");
            return;
        }

        clearPendingAttachGameEntry();
        if (attachResult == ATTACK_GAME_ENTRY_RESULT.MISSION_GAME_ENTRY_TYPE)
        {
            Debug.LogWarning("自动挂接GameEntry已取消,当前工程中未找到GameEntry类型");
            return;
        }
        if (attachResult == ATTACK_GAME_ENTRY_RESULT.MissingGameEntryNode)
        {
            Debug.LogWarning("自动挂接GameEntry已取消,启动场景中未找到根节点: " + GAME_ENTRY_NODE_NAME);
            return;
        }
        if (attachResult == ATTACK_GAME_ENTRY_RESULT.Cancelled)
        {
            Debug.Log("自动挂接GameEntry已取消,用户取消了保存当前场景");
            return;
        }
        Debug.LogWarning("自动挂接GameEntry已取消");
    }
    // 打开启动场景,并将用户工程中的GameEntry脚本挂到GameEntry根节点
    protected static ATTACK_GAME_ENTRY_RESULT attachGameEntryToStartScene(bool logError)
    {
        if (!hasStartScene())
        {
            if (logError)
            {
                Debug.LogError("未找到启动场景: " + START_SCENE);
            }
            return ATTACK_GAME_ENTRY_RESULT.MISSING_START_SCENE;
        }

        Type gameEntryType = findMonoBehaviourType(GAME_ENTRY_TYPE_NAME);
        if (gameEntryType == null)
        {
            if (logError)
            {
                Debug.LogWarning("未找到GameEntry类型: " + GAME_ENTRY_TYPE_NAME);
            }
            return ATTACK_GAME_ENTRY_RESULT.MISSION_GAME_ENTRY_TYPE;
        }

        if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
        {
            return ATTACK_GAME_ENTRY_RESULT.Cancelled;
        }

        Scene scene = EditorSceneManager.OpenScene(START_SCENE, OpenSceneMode.Single);
        GameObject gameEntryObject = scene.GetRootGameObjects().find(item => item.name == GAME_ENTRY_NODE_NAME);
        if (gameEntryObject == null)
        {
            if (logError)
            {
                Debug.LogError("启动场景中未找到根节点: " + GAME_ENTRY_NODE_NAME);
            }
            return ATTACK_GAME_ENTRY_RESULT.MissingGameEntryNode;
        }

        int count = GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(gameEntryObject);
        if (count > 0)
        {
            GameObjectUtility.RemoveMonoBehavioursWithMissingScript(gameEntryObject);
            EditorUtility.SetDirty(gameEntryObject);
            Debug.Log("已移除Missing Script数量: " + count + ", 节点: " + gameEntryObject.name);
        }

        if (gameEntryObject.GetComponent(gameEntryType) == null)
        {
            gameEntryObject.AddComponent(gameEntryType);
            EditorUtility.SetDirty(gameEntryObject);
            Debug.Log("已挂接GameEntry脚本: " + gameEntryType.FullName);
        }
        else
        {
            Debug.Log("GameEntry脚本已经存在: " + gameEntryType.FullName);
        }

        EditorSceneManager.MarkSceneDirty(scene);
        EditorSceneManager.SaveScene(scene);
        return ATTACK_GAME_ENTRY_RESULT.SUCCESS;
    }
    // 判断启动场景是否存在,同时兼容刚复制但AssetDatabase还没完全导入的情况
    protected static bool hasStartScene()
    {
        if (AssetDatabase.LoadAssetAtPath<SceneAsset>(START_SCENE) != null)
        {
            return true;
        }
        if (!File.Exists(getProjectRootPath() + START_SCENE))
        {
            return false;
        }
        AssetDatabase.ImportAsset(START_SCENE, ImportAssetOptions.ForceUpdate);
        return AssetDatabase.LoadAssetAtPath<SceneAsset>(START_SCENE) != null;
    }
    // 将启动场景添加到Build Settings第一位
    protected static void addStartSceneToBuildSettings()
    {
        if (!hasStartScene())
        {
            Debug.LogWarning("启动场景不存在,无法添加到Build Settings: " + START_SCENE);
            return;
        }

        EditorBuildSettingsScene[] oldScenes = EditorBuildSettings.scenes;
        for (int i = 0; i < oldScenes.Length; ++i)
        {
            if (oldScenes[i].path == START_SCENE)
            {
                if (!oldScenes[i].enabled)
                {
                    oldScenes[i].enabled = true;
                    EditorBuildSettings.scenes = oldScenes;
                }
                Debug.Log("启动场景已在Build Settings中: " + START_SCENE);
                return;
            }
        }

        EditorBuildSettingsScene[] newScenes = new EditorBuildSettingsScene[oldScenes.Length + 1];
        newScenes[0] = new EditorBuildSettingsScene(START_SCENE, true);
        for (int i = 0; i < oldScenes.Length; ++i)
        {
            newScenes[i + 1] = oldScenes[i];
        }

        EditorBuildSettings.scenes = newScenes;
        Debug.Log("已添加启动场景到Build Settings: " + START_SCENE);
    }
    // 请求初始化HybridCLR和Obfuz,安装包和添加宏以后,等待重新编译再写插件设置
    protected static void requestInitHybridCLRObfuz()
    {
        SessionState.SetInt(SESSION_HYBRIDCLR_OBFUZ_STATE, (int)HYBRIDCLR_OBFUZ_STATE.INSTALL_HYBRIDCLR);
        EditorApplication.delayCall += continueHybridCLRObfuzIfNeed;
        Debug.Log("开始初始化HybridCLR和Obfuz");
    }
    // 继续执行HybridCLR和Obfuz初始化
    protected static void continueHybridCLRObfuzIfNeed()
    {
        int state = SessionState.GetInt(SESSION_HYBRIDCLR_OBFUZ_STATE, (int)HYBRIDCLR_OBFUZ_STATE.NONE);
        if (state == (int)HYBRIDCLR_OBFUZ_STATE.NONE)
        {
            return;
        }
        if (EditorApplication.isCompiling || EditorApplication.isUpdating)
        {
            EditorApplication.delayCall += continueHybridCLRObfuzIfNeed;
            return;
        }
        if (state == (int)HYBRIDCLR_OBFUZ_STATE.INSTALL_HYBRIDCLR)
        {
            if (isPackageInstalled(HYBRIDCLR_PACKAGE_ID))
            {
                SessionState.SetInt(SESSION_HYBRIDCLR_OBFUZ_STATE, (int)HYBRIDCLR_OBFUZ_STATE.INSTALL_OBFUZ);
                EditorApplication.delayCall += continueHybridCLRObfuzIfNeed;
                return;
            }
            startInstallPackage(HYBRIDCLR_PACKAGE_URL);
            return;
        }
        if (state == (int)HYBRIDCLR_OBFUZ_STATE.INSTALL_OBFUZ)
        {
            if (isPackageInstalled(OBFUZ_PACKAGE_ID))
            {
                SessionState.SetInt(SESSION_HYBRIDCLR_OBFUZ_STATE, (int)HYBRIDCLR_OBFUZ_STATE.ADD_DEFINE);
                EditorApplication.delayCall += continueHybridCLRObfuzIfNeed;
                return;
            }
            startInstallPackage(OBFUZ_PACKAGE_URL);
            return;
        }
        if (state == (int)HYBRIDCLR_OBFUZ_STATE.ADD_DEFINE)
        {
            // 添加HybridCLR和Obfuz宏
            addDefineSymbols(USE_HYBRID_CLR, USE_OBFUZ);
            SessionState.SetInt(SESSION_HYBRIDCLR_OBFUZ_STATE, (int)HYBRIDCLR_OBFUZ_STATE.INIT_SETTING);
            AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate);
            CompilationPipeline.RequestScriptCompilation();
            Debug.Log("HybridCLR和Obfuz宏已添加,等待Unity重新编译后写入插件设置");
            return;
        }
        if (state == (int)HYBRIDCLR_OBFUZ_STATE.INIT_SETTING)
        {
            initHybridCLRObfuz();
            SessionState.SetInt(SESSION_HYBRIDCLR_OBFUZ_STATE, (int)HYBRIDCLR_OBFUZ_STATE.NONE);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("HybridCLR和Obfuz初始化完成");
        }
    }
    // 开始安装Package
    protected static void startInstallPackage(string packageUrl)
    {
        if (mPackageAddRequest != null)
        {
            return;
        }
        mPackageAddRequest = Client.Add(packageUrl);
        EditorApplication.update -= updateInstallPackage;
        EditorApplication.update += updateInstallPackage;
        Debug.Log("正在安装Package: " + packageUrl);
    }
    // 等待Package安装完成
    protected static void updateInstallPackage()
    {
        if (mPackageAddRequest == null || !mPackageAddRequest.IsCompleted)
        {
            return;
        }
        if (mPackageAddRequest.Status == StatusCode.Success)
        {
            Debug.Log("Package安装完成: " + mPackageAddRequest.Result.packageId);
            mPackageAddRequest = null;
            EditorApplication.update -= updateInstallPackage;
            int state = SessionState.GetInt(SESSION_HYBRIDCLR_OBFUZ_STATE, (int)HYBRIDCLR_OBFUZ_STATE.NONE);
            if (state == (int)HYBRIDCLR_OBFUZ_STATE.INSTALL_HYBRIDCLR)
            {
                SessionState.SetInt(SESSION_HYBRIDCLR_OBFUZ_STATE, (int)HYBRIDCLR_OBFUZ_STATE.INSTALL_OBFUZ);
            }
            else if (state == (int)HYBRIDCLR_OBFUZ_STATE.INSTALL_OBFUZ)
            {
                SessionState.SetInt(SESSION_HYBRIDCLR_OBFUZ_STATE, (int)HYBRIDCLR_OBFUZ_STATE.ADD_DEFINE);
            }
            EditorApplication.delayCall += continueHybridCLRObfuzIfNeed;
            return;
        }
        Debug.LogError("Package安装失败: " + mPackageAddRequest.Error.message);
        mPackageAddRequest = null;
        EditorApplication.update -= updateInstallPackage;
        SessionState.SetInt(SESSION_HYBRIDCLR_OBFUZ_STATE, (int)HYBRIDCLR_OBFUZ_STATE.NONE);
    }
    // 初始化HybridCLR和Obfuz,修改生成文件路径,取消混淆Obfuz运行时,并设置需要混淆的热更程序集
    protected static void initHybridCLRObfuz()
    {
#if USE_OBFUZ
        createDir(getFilePath(OBFUZ_OUTPUT_PATH));

        bool obfuzChanged = false;
        if (setObfuzCodeOutputPath(OBFUZ_OUTPUT_PATH))
        {
            obfuzChanged = true;
            Debug.Log("已设置Obfuz生成文件路径: " + OBFUZ_OUTPUT_PATH);
        }

        if (setObfuzAssemblySettings())
        {
            obfuzChanged = true;
            Debug.Log("已设置Obfuz混淆程序集: " + HOTFIX_FRAME + ", " + HOTFIX);
        }

        if (obfuzChanged)
        {
            ObfuzSettings.Save();
        }
#endif
#if USE_HYBRID_CLR
        createDir("Assets/Scripts/AutoGenerated/HybridCLRGenerate");

        HybridCLRSettings.Instance.outputAOTGenericReferenceFile = HYBRIDCLR_AOT_OUTPUT_PATH;
        HybridCLRSettings.Instance.hotUpdateAssemblyDefinitions = addAsmdefToArray(
            HybridCLRSettings.Instance.hotUpdateAssemblyDefinitions, HOTFIX_FRAME, HOTFIX);

        HybridCLRSettings.Save();

        Debug.Log("已设置HybridCLR生成文件路径: " + HYBRIDCLR_AOT_OUTPUT_PATH);
        Debug.Log("已设置HybridCLR热更新程序集: Frame_HotFix, HotFix");
#else
	Debug.LogWarning("未启用USE_HYBRID_CLR宏,跳过HybridCLR设置");
#endif
    }
#if USE_HYBRID_CLR
    // 向AssemblyDefinitionAsset数组中添加asmdef,已存在则不重复添加
    protected static AssemblyDefinitionAsset[] addAsmdefToArray(AssemblyDefinitionAsset[] array, params string[] asmdefNames)
    {
        List<AssemblyDefinitionAsset> list = new();
        foreach (AssemblyDefinitionAsset item in array.safe())
        {
            list.addUniqueIf(item, item != null);
        }
        foreach (string name in asmdefNames)
        {
            AssemblyDefinitionAsset asmdef = findAsmdefByFileName(name);
            if (asmdef == null)
            {
                Debug.LogError("未找到asmdef:" + name);
                continue;
            }
            list.addUnique(asmdef);
        }
        return list.ToArray();
    }
    // 根据asmdef文件名查找AssemblyDefinitionAsset
    protected static AssemblyDefinitionAsset findAsmdefByFileName(string asmdefName)
    {
        foreach (string guid in AssetDatabase.FindAssets("t:AssemblyDefinitionAsset"))
        {
            string assetPath = AssetDatabase.GUIDToAssetPath(guid);
            if (Path.GetFileNameWithoutExtension(assetPath) == asmdefName)
            {
                return AssetDatabase.LoadAssetAtPath<AssemblyDefinitionAsset>(assetPath);
            }
        }
        return null;
    }
#endif
#if USE_OBFUZ
    // 设置Obfuz生成文件路径
    protected static bool setObfuzCodeOutputPath(string outputPath)
    {
        ObfuzSettings settings = ObfuzSettings.Instance;
        if (settings == null)
        {
            Debug.LogWarning("未找到ObfuzSettings,跳过Obfuz设置");
            return false;
        }
        settings.encryptionVMSettings ??= new EncryptionVMSettings();
        if (settings.encryptionVMSettings.codeOutputPath == outputPath)
        {
            return false;
        }
        settings.encryptionVMSettings.codeOutputPath = outputPath;
        EditorUtility.SetDirty(settings);
        return true;
    }
    // 设置Obfuz程序集配置:取消Obfuscate Obfuz Runtime,并添加热更程序集到Assemblies To Obfuscate
    protected static bool setObfuzAssemblySettings()
    {
        ObfuzSettings settings = ObfuzSettings.Instance;
        if (settings == null)
        {
            Debug.LogWarning("未找到ObfuzSettings,跳过Obfuz程序集设置");
            return false;
        }
        settings.assemblySettings ??= new AssemblySettings();
        bool changed = false;
        if (settings.assemblySettings.obfuscateObfuzRuntime)
        {
            settings.assemblySettings.obfuscateObfuzRuntime = false;
            changed = true;
        }

        string[] oldAssemblies = settings.assemblySettings.assembliesToObfuscate;
        string[] newAssemblies = addStringToArray(oldAssemblies, HOTFIX_FRAME, HOTFIX);
        if (newAssemblies != oldAssemblies)
        {
            settings.assemblySettings.assembliesToObfuscate = newAssemblies;
            changed = true;
        }
        if (changed)
        {
            EditorUtility.SetDirty(settings);
        }
        return changed;
    }
    // 向字符串数组中添加字符串,已存在则不重复添加
    protected static string[] addStringToArray(string[] array, params string[] values)
    {
        List<string> list = new();
        foreach (string item in array)
        {
            list.addUniqueIf(item, !item.isEmpty());
        }
        bool changed = false;
        foreach (string item in values)
        {
            if (list.addUniqueIf(item, !item.isEmpty()))
            {
                changed = true;
            }
        }
        return changed ? list.ToArray() : array;
    }
#endif
    // 判断Package是否已经安装。
    // 根据包名查找PackageInfo,兼容没有PackageInfo.FindForPackageName的Unity版本。
    public static bool isPackageInstalled(string packageName)
    {
        if (string.IsNullOrEmpty(packageName))
        {
            Debug.LogError("Package name cannot be null or empty.");
            return false;
        }
        foreach (var packageInfo in UnityEditor.PackageManager.PackageInfo.GetAllRegisteredPackages().safe())
        {
            if (packageInfo != null && packageInfo.name == packageName)
            {
                return true;
            }
        }
        return false;
    }
    // 添加宏到常用平台
    protected static void addDefineSymbols(params string[] symbols)
    {
        HashSet<BuildTargetGroup> groupSet = new()
        {
            EditorUserBuildSettings.selectedBuildTargetGroup,
            BuildTargetGroup.Standalone,
            BuildTargetGroup.Android,
            BuildTargetGroup.iOS,
            BuildTargetGroup.WebGL,
        };
        foreach (BuildTargetGroup group in groupSet)
        {
            if (group == BuildTargetGroup.Unknown)
            {
                continue;
            }
            var buildTarget = NamedBuildTarget.FromBuildTargetGroup(group);
            string defineText = PlayerSettings.GetScriptingDefineSymbols(buildTarget);
            HashSet<string> defineSet = new(defineText.Split(';', StringSplitOptions.RemoveEmptyEntries));
            bool changed = false;
            foreach (string symbol in symbols)
            {
                if (defineSet.Add(symbol))
                {
                    changed = true;
                }
            }
            if (!changed)
            {
                return;
            }
            PlayerSettings.SetScriptingDefineSymbols(buildTarget, string.Join(";", defineSet));
            Debug.Log("已添加宏到" + group + ": " + string.Join(",", symbols));
        }
    }
    // 通过类型名查找MonoBehaviour类型,避免Editor_Frame直接引用Game程序集
    protected static Type findMonoBehaviourType(string typeName)
    {
        foreach (System.Reflection.Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            Type type = assembly.GetType(typeName);
            if (type != null && typeof(MonoBehaviour).IsAssignableFrom(type))
            {
                return type;
            }
        }
        foreach (System.Reflection.Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            foreach (Type type in assembly.GetTypes())
            {
                if (type.Name == typeName && typeof(MonoBehaviour).IsAssignableFrom(type))
                {
                    return type;
                }
            }
        }
        return null;
    }
    // 判断复制的文件是否会触发脚本编译
    protected static bool isScriptCompileFile(string filePath)
    {
        string extension = Path.GetExtension(filePath);
        return extension == ".cs" ||
               extension == ".asmdef" ||
               extension == ".asmref" ||
               extension == ".rsp";
    }
    // 获取当前包的真实路径,用于识别旧SessionState是否属于当前安装的包
    protected static string getCurrentPackagePath()
    {
        var packageInfo = UnityEditor.PackageManager.PackageInfo.FindForAssembly(typeof(MenuInit).Assembly);
        if (packageInfo != null && !packageInfo.resolvedPath.isEmpty())
        {
            return packageInfo.resolvedPath.Replace("\\", "/");
        }
        return typeof(MenuInit).Assembly.FullName;
    }
    // 获取Unity工程根目录
    protected static string getProjectRootPath()
    {
        string dataPath = Application.dataPath.Replace("\\", "/");
        return Directory.GetParent(dataPath)?.FullName.Replace("\\", "/") + "/";
    }
}