#pragma once

#include <wx/frame.h>
#include <wx/minifram.h>
#include <wx/app.h>
#include <wx/wx.h>
#include <wx/wxprec.h>
#include <wx/string.h>
#include <wx/aui/auibar.h>
#include <wx/msw/toolbar.h>
#include <wx/aui/framemanager.h>
#include <wx/aui/aui.h>
#include <wx/toolbar.h>
#include <wx/tbarbase.h>
#include <wx/listctrl.h>
#include <wx/listbox.h>
#include <wx/panel.h>
#include <wx/timer.h>
#include <wx/textctrl.h>
#include <wx/msw/filedlg.h>
#include <wx/treectrl.h>
#include <wx/msw/slider.h>
#include <wx/artprov.h>
#include <wx/xrc/xmlres.h>
#include <wx/intl.h>
#include <wx/colour.h>
#include <wx/settings.h>
#include <wx/font.h>
#include <wx/grid.h>
#include <wx/gdicmn.h>
#include <wx/sizer.h>
#include <wx/clipbrd.h>
#include <wx/log.h>
#include <wx/cmdline.h>